version: '3.8'

services:
  traefik:
    image: traefik:v2.9
    container_name: traefik
    security_opt:
      - no-new-privileges:true
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml
    ports:
      - "80:80"
      - "8080:8080"  # Dashboard (solo localhost)
    networks:
      - traefik_network
    labels:
      - "traefik.enable=true"
      # Dashboard solo accesible desde localhost
      - "traefik.http.routers.traefik.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=web"

  servicio-analiticas:
    build: ./servicio-analiticas
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-registro.rule=PathPrefix(`/reporte`)"
      - "traefik.http.routers.api-registro.entrypoints=web"
      - "traefik.http.routers.api-registro.middlewares=auth-basic"
      - "traefik.http.middlewares.auth-basic.basicauth.users=admin:$$apr1$$Z1sbqKz8$$4/g3NzDCqLE/tURphL2vb1"  # admin:secret
      - "traefik.http.services.api-registro.loadbalancer.server.port=3000"
      - "traefik.http.routers.api-registro.middlewares=auth-basic,cors-headers"
      - "traefik.http.middlewares.cors-headers.headers.accesscontrolallowmethods=GET,POST"
    networks:
      - traefik_network

  servicio-cliente-uno:
    build: ./servicio-cliente
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cliente-app1.rule=PathPrefix(`/cliente/uno`)"
      - "traefik.http.routers.cliente-app1.entrypoints=web"
      - "traefik.http.routers.cliente-app1.middlewares=strip-app1"
      - "traefik.http.middlewares.strip-app1.stripprefix.prefixes=/cliente/uno"
      - "traefik.http.services.cliente-app1.loadbalancer.server.port=3001"
    environment:
      - SERVICE_ID=cliente-uno
    networks:
      - traefik_network

  servicio-cliente-dos:
    build: ./servicio-cliente
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cliente-app2.rule=PathPrefix(`/cliente/dos`)"
      - "traefik.http.routers.cliente-app2.entrypoints=web"
      - "traefik.http.routers.cliente-app2.middlewares=strip-app2"
      - "traefik.http.middlewares.strip-app2.stripprefix.prefixes=/cliente/dos"
      - "traefik.http.services.cliente-app2.loadbalancer.server.port=3001"
    environment:
      - SERVICE_ID=cliente-dos
    networks:
      - traefik_network

  panel-visual:
    build: ./panel-visual
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.monitor.rule=PathPrefix(`/panel`)"
      - "traefik.http.routers.monitor.entrypoints=web"
      - "traefik.http.services.monitor.loadbalancer.server.port=80"
      - "traefik.http.routers.monitor.middlewares=strip-monitor"
      - "traefik.http.middlewares.strip-monitor.stripprefix.prefixes=/panel"
    networks:
      - traefik_network

networks:
  traefik_network:
    driver: bridge
